########################Log
logging:
  path: /data/nadmin/logs

server:
  schedule:
    pool: 10
## sftp 配置
sftp:
  host: 127.0.0.1
  password: CMm5FX4DZ1
  port: 22
  user: publisher
#####################DB
sharding:
  jdbc:
    datasource:
      ds:
        jdbc-url: jdbc:mysql://127.0.0.1:3307/short_link?autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
        username: run_master
        password: '26H1gKG@SOwpwtYn4'
        maximum-pool-size: 100
        minimum-idle: 10  # 最小空闲连接数量
########################Redis
spring:
  redis:
    host: 127.0.0.1
    password: 'asdf#2022'
    port: 8001
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 20
######################## Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
